services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gpty-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend 

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gpty-backend
    ports:
      - "8001:8001"
    env_file:
      - ./backend/.env